version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projetdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: projetdb
    networks:
      - app_network
    restart: always

  frontend:
    build: ./nginx
    container_name: frontend_container
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data: 